apiVersion: v1
kind: Service
metadata:
  name: java-cicd-app-service
  namespace: default
spec:
  selector:
    app: java-cicd-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080