pipeline
{
    agent any
    environment 
    {
  IMAGE_NAME="2025vaishnavi/sprindboot-app"
    }


stages
{
stage('Checkout')
{
    steps
    {
          checkout scm
    }
}
stage('build')
{
steps{
    dir('app'){
    sh 'mvn clean package'
    }
}
}
stage('Docker Build')
{
    steps{
        dir('app'){
        sh 'docker build -t $IMAGE_NAME:${BUILD_NUMBER} .'
    }
    }
}

stage('Docker Puch')
{
    steps{
        withCredentials([usernamePassword(credentialsId:'docker-cred',
                        usernameVariable:'Docker_User',
                        passwordVariable:'Docker_Pass')])
        
        {
            sh '''
            echo $Docker_Pass | docker login -u $Docker_User --password-stdin
             docker push $IMAGE_NAME:${BUILD_NUMBER}
              '''
        }
    }
}

stage('Deploy')
{
 steps{
    echo 'deployement handle by argocd'
 }
}
}

}