pipeline {
    agent any

    environment {
        IMAGE_NAME = "2025vaishnavi/sprindboot-app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('app') {
                    sh 'docker build -t $IMAGE_NAME:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-cred',
                        usernameVariable: 'Docker_User',
                        passwordVariable: 'Docker_Pass'
                    )
                ]) {
                    sh '''
                    echo $Docker_Pass | docker login -u $Docker_User --password-stdin
                    docker push $IMAGE_NAME:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Update Deployment') {
            steps {
                sh 'git branch -a'
                sh 'git remote -v'
                sh """
                sed -i 's#image:.*#image: ${IMAGE_NAME}:${BUILD_NUMBER}#' k8s/deployment.yaml

                git config --global user.email "vaishnavijpawar4@gmail.com"
                git config --global user.name "vaishnavi"

                git add k8s/deployment.yaml
                git commit -m "Update image ${BUILD_NUMBER}" || true
                git push origin main
                """
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deployment handled by ArgoCD'
            }
        }
    }
}